Attribute VB_Name = "modMockLlm3"
Option Explicit

' ============================================================================
' modMockLlm3 - mock応答(S2)の本体。12章§2 の30,000字契約による modMockLlm の
'   分割先(modMockLlm1..n の規約。v2.4.1)。W7(17章 T-55・裁定書25)で
'   15章§8.1 の MK-S2-NEW / MK-S2-RNW が insurability の gap_note 分離・
'   新規案件の gaps 2件・純資産との対比つき loss_scale_note を持つようになり、
'   modMockLlm が上限に達したため切り出した。
'
' 応答の正は 15章§8.1 の表。呼び口は modMockLlm.ResponseById のままであり、
'   本モジュールは JSON を組み立てて返すだけの決定的な関数を持つ(乱数・時刻・
'   呼び出し回数の状態を持たない。15章§8.2 の状態レス規約)。
'
' R4準拠(12章§2): Excel/COMトークンを1つも持たない純文字列モジュール。
' CP932準拠(15章§0 原則7)。
' ============================================================================

Public Function BuildS2NewJson() As String
    Dim s As String

    s = s & "{""risks"":[{""risk_no"":1,""category"":""manufacturing_quality"",""risk_name"":""アレルゲン表示誤りによる自主回収"",""scenario"":""繁忙期の増産で表示チェック体制が薄まり、アレルゲン表示を誤った商品が出荷されて自主回収に至る"",""status"":""proposed"",""frequency"":""mid"",""impact"":""large"",""frequency_score"":3,""impact_score"":4,""evidence"":{""quote"":""季節限定商品の開発強化"",""source"":""hp""},""insurability"":{""transferability"":""cover"",""line_note"":""生産物賠償責任保険(PL保険)"",""gap_note"":""リコール費用特約の有無と自主回収費用の担保範囲"",""control_note"":""表示チェック体制の二重化""},""loss_scale_note"":"""",""check_points"":[""表示チェック工程のダブルチェック運用有無"",""アレルゲン専用ライン分離の有無""],""preventions""" & vbLf
    s = s & ":[{""measure"":""出荷前のアレルゲン表示ダブルチェック体制を構築する"",""related_menu_id"":""M-0012""}]},{""risk_no"":2,""category"":""supply_chain"",""risk_name"":""乳製品・果実の調達難による生産停滞"",""scenario"":""産地不作や輸入価格の高騰で主要原材料の調達が滞り、生産計画に遅れが生じる"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score"":3,""evidence"":{""quote"":""季節や産地不作の影響を受けやすい"",""source"":""hp""},""insurability"":{""transferability"":""partial"",""line_note"":""仕入先費用保険・利益保険(BI)"",""gap_note"":""契約者外の産地不作が担保事故に当たるか"",""control_note"":""仕入先の複数化・在庫積み増し""},""loss_scale_note"":"""",""check_points"":[" & vbLf
    s = s & """主要原材料の仕入先数"",""在庫の積み増し余地""],""preventions"":[{""measure"":""主要原材料の仕入先複数化を検討する"",""related_menu_id"":""""}]},{""risk_no"":3,""category"":""facility_bcp"",""risk_name"":""浸水による浜松本社工場の操業停止"",""scenario"":""豪雨により本社工場周辺が浸水想定深に達し、主力ラインが長期間停止する"",""status"":""proposed"",""frequency"":""low"",""impact"":""large"",""frequency_score"":2,""impact_score"":4,""evidence"":{""quote"":""浸水想定区域内(想定浸水深0.5メートルから3.0メートル)"",""source"":""hp""},""insurability"":{""transferability"":""cover"",""line_note"":""火災保険(水災担保)・利益保険(BI)"",""gap_note"":""水災の免責金額と復旧期間の限度"",""control_note"":""止水板の設置・BCP発動基準の整備""" & vbLf
    s = s & "},""loss_scale_note"":"""",""check_points"":[""止水板等の水災対策の有無"",""BCP発動基準の整備状況""],""preventions"":[{""measure"":""止水板設置とBCP発動基準を整備する"",""related_menu_id"":""M-0012""},{""measure"":""主力ラインの一部を高所へ移設することを検討する"",""related_menu_id"":""""}]},{""risk_no"":4,""category"":""hr_labor"",""risk_name"":""パート比率の高さによる繁忙期の人手不足"",""scenario"":""繁忙期にパート従業員が確保できず、増産計画に対応できなくなる"",""status"":""proposed"",""frequency"":""high"",""impact"":""mid"",""frequency_score"":4,""impact_score"":3,""evidence"":{""quote"":""パート従業員の比率が高く"",""source"":""hp""},""insurability"":{""transferability""" & vbLf
    s = s & ":""hard"",""line_note"":""労働災害総合保険(法定外補償)"",""gap_note"":""パート従業員が被保険者に含まれるか"",""control_note"":""繁忙期の応援体制整備・多能工化""},""loss_scale_note"":"""",""check_points"":[""繁忙期の応援体制の有無"",""多能工化の進捗""],""preventions"":[{""measure"":""多能工化研修を実施する"",""related_menu_id"":""""}]},{""risk_no"":5,""category"":""digital_info"",""risk_name"":""ECサイト刷新に伴う個人情報漏えい"",""scenario"":""刷新した自社ECサイトの脆弱性を突かれ、顧客の個人情報が外部に流出する"",""status"":""proposed"",""frequency"":""mid"",""impact"":""large"",""frequency_score"":3,""impact_score"":4,""evidence"":{""quote"":""自社ECサイトを刷新した"",""source"":""hp""},""insurability"":{""transferability""" & vbLf
    s = s & ":""cover"",""line_note"":""サイバー保険"",""gap_note"":""個人情報漏えい対応費用と利益損害の限度額"",""control_note"":""脆弱性診断の定期実施""},""loss_scale_note"":"""",""check_points"":[""ECサイトの脆弱性診断の実施状況"",""個人情報保護体制の整備状況""],""preventions"":[{""measure"":""ECサイトの脆弱性診断を定期実施する"",""related_menu_id"":""""}]},{""risk_no"":6,""category"":""strategy_market"",""risk_name"":""国内菓子市場の縮小による需要減"",""scenario"":""国内の菓子市場が緩やかに縮小し、既存商品の販売数量が伸び悩む"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score"":3,""evidence"":{""quote"":""国内の菓子市場は縮小傾向"",""source"":""knowledge""" & vbLf
    s = s & "},""insurability"":{""transferability"":""hard"",""line_note"":""該当する既存種目なし"",""gap_note"":""需要減は保険事故に当たらず移転できない"",""control_note"":""EC直販拡大・新商品開発での需要創出""},""loss_scale_note"":"""",""check_points"":[""EC直販比率の推移"",""新商品の開発ペース""],""preventions"":[{""measure"":""EC直販チャネルの拡大を継続する"",""related_menu_id"":""""}]},{""risk_no"":7,""category"":""legal_regulatory"",""risk_name"":""食品表示法改正への対応遅れ"",""scenario"":""食品表示制度の改正に表示ルールの改訂が追いつかず、指摘や回収につながる"",""status"":""proposed"",""frequency"":""low"",""impact"":""mid"",""frequency_score"":2,""impact_score"":3,""evidence"":{""quote"":""食品表示""," & vbLf
    s = s & """source"":""knowledge""},""insurability"":{""transferability"":""partial"",""line_note"":""生産物賠償責任保険(PL保険)"",""gap_note"":""法令違反に起因する損害の免責条項の範囲"",""control_note"":""表示ルールの定期チェック体制""},""loss_scale_note"":"""",""check_points"":[""表示ルール改訂への追随体制""],""preventions"":[{""measure"":""表示ルールの定期チェック体制を整備する"",""related_menu_id"":""""}]},{""risk_no"":8,""category"":""sales_customer"",""risk_name"":""EC物流委託先の代替不能による配送遅延"",""scenario"":""EC直販の配送を担う外部委託先1社にトラブルが起き、代替手段が無いまま配送が滞る"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score""" & vbLf
    s = s & ":3,""evidence"":{""quote"":""外部委託先1社に依存しており"",""source"":""memo""},""insurability"":{""transferability"":""partial"",""line_note"":""利益保険(BI)の拡張担保"",""gap_note"":""委託先起因の操業停止が担保事故に当たるか"",""control_note"":""物流委託先の複線化検討""},""loss_scale_note"":"""",""check_points"":[""物流委託先の複線化の可否""],""preventions"":[{""measure"":""物流委託先の複線化を検討する"",""related_menu_id"":""""}]}]," & vbLf
    s = s & """gaps"":[{""gap_no"":1,""gap_type"":""uninsured"",""target"":""サイバー(個人情報漏えい)"",""description"":""(確度低・付保の見立てに基づく推定)EC刷新に伴う漏えいに備えるサイバー保険は未付保とみられる"",""risk_evidence"":""自社ECサイトを刷新した"",""coverage_evidence"":""該当契約なし""},{""gap_no"":2,""gap_type"":""uninsured"",""target"":""利益(BI)"",""description"":""(確度低・付保の見立てに基づく推定)浸水による操業停止の利益損害を担保する契約が見当たらない"",""risk_evidence"":""浸水想定区域内(想定浸水深0.5メートルから3.0メートル)"",""coverage_evidence"":""元請の包括契約に労災上乗せが乗っている模様(付保の見立て)""}],""emerging_risks"":[{""risk_name"":""気候変動による原料調達難と工場の高温化"",""category"":""facility_bcp"",""horizon"":""mid_long"",""scenario"":""果実や乳製品の産地不作が頻発すると原料調達が不安定化し、浜松2工場の夏季高温化が空調負荷や品質管理コストを押し上げる可能性がある"",""evidence_quote""" & vbLf
    s = s & ":""季節や産地不作の影響を受けやすい"",""evidence_source"":""hp"",""proposal_hint"":""原料調達の多元化提案と工場の空調・BCP診断メニューの提案に接続できる""}],""open_questions"":[""主要原材料の仕入先は何社に分散しているか"",""EC物流の代替委託先を確保する計画はあるか""]}"

    BuildS2NewJson = s
End Function

Public Function BuildS2RnwJson() As String
    Dim s As String

    s = s & "{""risks"":[{""risk_no"":1,""category"":""manufacturing_quality"",""risk_name"":""アレルゲン表示誤りによる自主回収"",""scenario"":""繁忙期の増産で表示チェック体制が薄まり、アレルゲン表示を誤った商品が出荷されて自主回収に至る"",""status"":""proposed"",""frequency"":""mid"",""impact"":""large"",""frequency_score"":3,""impact_score"":4,""evidence"":{""quote"":""季節限定商品の開発強化"",""source"":""hp""},""insurability"":{""transferability"":""cover"",""line_note"":""生産物賠償責任保険(PL保険)"",""gap_note"":""リコール費用特約の有無と自主回収費用の担保範囲"",""control_note"":""表示チェック体制の二重化""},""loss_scale_note"":"""",""check_points"":[""表示チェック工程のダブルチェック運用有無"",""アレルゲン専用ライン分離の有無""],""preventions""" & vbLf
    s = s & ":[{""measure"":""出荷前のアレルゲン表示ダブルチェック体制を構築する"",""related_menu_id"":""M-0012""}]},{""risk_no"":2,""category"":""supply_chain"",""risk_name"":""乳製品・果実の調達難による生産停滞"",""scenario"":""産地不作や輸入価格の高騰で主要原材料の調達が滞り、生産計画に遅れが生じる"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score"":3,""evidence"":{""quote"":""季節や産地不作の影響を受けやすい"",""source"":""hp""},""insurability"":{""transferability"":""partial"",""line_note"":""仕入先費用保険・利益保険(BI)"",""gap_note"":""契約者外の産地不作が担保事故に当たるか"",""control_note"":""仕入先の複数化・在庫積み増し""},""loss_scale_note"":"""",""check_points"":[" & vbLf
    s = s & """主要原材料の仕入先数"",""在庫の積み増し余地""],""preventions"":[{""measure"":""主要原材料の仕入先複数化を検討する"",""related_menu_id"":""""}]},{""risk_no"":3,""category"":""facility_bcp"",""risk_name"":""浸水による浜松本社工場の操業停止"",""scenario"":""豪雨により本社工場周辺が浸水想定深に達し、主力ラインが長期間停止する"",""status"":""proposed"",""frequency"":""low"",""impact"":""large"",""frequency_score"":2,""impact_score"":4,""evidence"":{""quote"":""浸水想定区域内(想定浸水深0.5メートルから3.0メートル)"",""source"":""hp""},""insurability"":{""transferability"":""cover"",""line_note"":""火災保険(水災担保)・利益保険(BI)"",""gap_note"":""水災の免責金額と復旧期間の限度"",""control_note"":""止水板の設置・BCP発動基準の整備""" & vbLf
    s = s & "},""loss_scale_note"":""純資産12億円に対し損害3億円規模(概算)"",""check_points"":[""止水板等の水災対策の有無"",""BCP発動基準の整備状況""],""preventions"":[{""measure"":""止水板設置とBCP発動基準を整備する"",""related_menu_id"":""M-0012""},{""measure"":""主力ラインの一部を高所へ移設することを検討する"",""related_menu_id"":""""}]},{""risk_no"":4,""category"":""hr_labor"",""risk_name"":""パート比率の高さによる繁忙期の人手不足"",""scenario"":""繁忙期にパート従業員が確保できず、増産計画に対応できなくなる"",""status"":""proposed"",""frequency"":""high"",""impact"":""mid"",""frequency_score"":4,""impact_score"":3,""evidence"":{""quote"":""パート従業員の比率が高く"",""source"":""hp""},""insurability"":{""transferability""" & vbLf
    s = s & ":""hard"",""line_note"":""労働災害総合保険(法定外補償)"",""gap_note"":""パート従業員が被保険者に含まれるか"",""control_note"":""繁忙期の応援体制整備・多能工化""},""loss_scale_note"":"""",""check_points"":[""繁忙期の応援体制の有無"",""多能工化の進捗""],""preventions"":[{""measure"":""多能工化研修を実施する"",""related_menu_id"":""""}]},{""risk_no"":5,""category"":""digital_info"",""risk_name"":""ECサイト刷新に伴う個人情報漏えい"",""scenario"":""刷新した自社ECサイトの脆弱性を突かれ、顧客の個人情報が外部に流出する"",""status"":""proposed"",""frequency"":""mid"",""impact"":""large"",""frequency_score"":3,""impact_score"":4,""evidence"":{""quote"":""自社ECサイトを刷新した"",""source"":""hp""},""insurability"":{""transferability""" & vbLf
    s = s & ":""cover"",""line_note"":""サイバー保険"",""gap_note"":""個人情報漏えい対応費用と利益損害の限度額"",""control_note"":""脆弱性診断の定期実施""},""loss_scale_note"":"""",""check_points"":[""ECサイトの脆弱性診断の実施状況"",""個人情報保護体制の整備状況""],""preventions"":[{""measure"":""ECサイトの脆弱性診断を定期実施する"",""related_menu_id"":""""}]},{""risk_no"":6,""category"":""strategy_market"",""risk_name"":""国内菓子市場の縮小による需要減"",""scenario"":""国内の菓子市場が緩やかに縮小し、既存商品の販売数量が伸び悩む"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score"":3,""evidence"":{""quote"":""国内の菓子市場は縮小傾向"",""source"":""knowledge""" & vbLf
    s = s & "},""insurability"":{""transferability"":""hard"",""line_note"":""該当する既存種目なし"",""gap_note"":""需要減は保険事故に当たらず移転できない"",""control_note"":""EC直販拡大・新商品開発での需要創出""},""loss_scale_note"":"""",""check_points"":[""EC直販比率の推移"",""新商品の開発ペース""],""preventions"":[{""measure"":""EC直販チャネルの拡大を継続する"",""related_menu_id"":""""}]},{""risk_no"":7,""category"":""legal_regulatory"",""risk_name"":""食品表示法改正への対応遅れ"",""scenario"":""食品表示制度の改正に表示ルールの改訂が追いつかず、指摘や回収につながる"",""status"":""proposed"",""frequency"":""low"",""impact"":""mid"",""frequency_score"":2,""impact_score"":3,""evidence"":{""quote"":""食品表示""," & vbLf
    s = s & """source"":""knowledge""},""insurability"":{""transferability"":""partial"",""line_note"":""生産物賠償責任保険(PL保険)"",""gap_note"":""法令違反に起因する損害の免責条項の範囲"",""control_note"":""表示ルールの定期チェック体制""},""loss_scale_note"":"""",""check_points"":[""表示ルール改訂への追随体制""],""preventions"":[{""measure"":""表示ルールの定期チェック体制を整備する"",""related_menu_id"":""""}]},{""risk_no"":8,""category"":""sales_customer"",""risk_name"":""EC物流委託先の代替不能による配送遅延"",""scenario"":""EC直販の配送を担う外部委託先1社にトラブルが起き、代替手段が無いまま配送が滞る"",""status"":""proposed"",""frequency"":""mid"",""impact"":""mid"",""frequency_score"":3,""impact_score""" & vbLf
    s = s & ":3,""evidence"":{""quote"":""外部委託先1社に依存しており"",""source"":""memo""},""insurability"":{""transferability"":""partial"",""line_note"":""利益保険(BI)の拡張担保"",""gap_note"":""委託先起因の操業停止が担保事故に当たるか"",""control_note"":""物流委託先の複線化検討""},""loss_scale_note"":"""",""check_points"":[""物流委託先の複線化の可否""],""preventions"":[{""measure"":""物流委託先の複線化を検討する"",""related_menu_id"":""""}]}],""gaps"":[{""gap_no"":1,""gap_type"":""uninsured"",""target"":""サイバー(個人情報漏えい)"",""description"":""EC刷新に伴う個人情報漏えいに備えるサイバー保険が現契約に見当たらない"",""risk_evidence"":""自社ECサイトを刷新した"",""coverage_evidence"":""該当契約なし""},{""gap_no""" & vbLf
    s = s & ":2,""gap_type"":""underinsured"",""target"":""生産物賠償責任保険(PL保険)"",""description"":""リコール費用特約が付いておらず自主回収時の費用が担保されない疑いがある"",""risk_evidence"":""アレルゲン表示誤りによる自主回収"",""coverage_evidence"":""1事故あたり1億円・リコール費用特約なし""},{""gap_no"":3,""gap_type"":""overlap"",""target"":""労働災害総合保険"",""description"":""パート従業員向けの法定外補償の範囲が別契約と重複している可能性がある"",""risk_evidence"":""パート従業員の比率が高く"",""coverage_evidence"":""パート従業員の加入状況は不明""}],""emerging_risks"":[],""open_questions"":[""主要原材料の仕入先は何社に分散しているか"",""EC物流の代替委託先を確保する計画はあるか""]}"

    BuildS2RnwJson = s
End Function
