Attribute VB_Name = "modMockLlm4"
Option Explicit

' ============================================================================
' modMockLlm4 - mock応答(S5 顧客向け提案書)の本体。15章§5.6「mock 応答(MK-S5)」
' ----------------------------------------------------------------------------
' 12章§2 の30,000字契約による modMockLlm の分割先(modMockLlm1..n の規約)。
' 呼び口は modMockLlm.ResponseById("MK-S5") のままで、本モジュールは JSON を
'   返すだけの決定的な関数を持つ(乱数・時刻・呼び出し回数の状態を持たない。
'   15章§8.2 の状態レス規約)。
'
' 受入条件(15章§5.6):
'   ・modValidate4.CheckS5 が1件も発火しない(V-S5-13 の警告も出ない)。
'   ・本文に対訳表の社内語(禁止語)を1語も含まない。
'   ・`"},` を含まない整形JSON(16章 E-63・tools/ribbon_wire_check.py)。
'     閉じ括弧の直前で必ず改行しているのはこのためであり、見た目の都合ではない。
'
' 企業は15章§8.1 と同じ架空の「株式会社浜松スイーツファクトリー」。risk_no は
'   MK-S2-RNW の 1..8 と対応する(hard_risks は 2 / 4 / 6 / 8)。
' R4準拠: Excel/COMトークンを1つも持たない純文字列モジュール。CP932準拠。
' ============================================================================

' BuildS5Json - MK-S5(15章§5.6)。22枚ぶんの文章と発表者ノートを返す。
Public Function BuildS5Json() As String
    Dim s As String
    s = "{" & vbLf
    s = s & " ""title"": ""経営リスク分析と保険活用のご提案""," & vbLf
    s = s & " ""subtitle"": ""浜松の菓子づくりを、次の成長に耐えるかたちへ""," & vbLf
    s = s & " ""themes"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""name"": ""事業を止めない""," & vbLf
    s = s & "   ""headline"": ""製造と販売と通信販売が同時に止まる連鎖を、復旧までの時間で設計し直します""," & vbLf
    s = s & "   ""body"": ""浜松の2工場と直販の通信販売が一本の流れでつながっているため、1か所の事故が出荷と売上の全体に広がります。建物や設備の補償だけでなく、復旧までの時間を目安にした備えの組み立てが要点になります。""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""name"": ""ブランドを守る""," & vbLf
    s = s & "   ""headline"": ""表示の誤りと情報の流出という、信用に直結する2つの事故に先に手を当てます""," & vbLf
    s = s & "   ""body"": ""季節限定商品の増産期は表示の確認が薄くなりやすく、自主回収は売上よりも信用の損失が大きくなります。通信販売の刷新で預かる情報も増えました。この2つを優先してご提案します。""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""name"": ""成長を後押しする""," & vbLf
    s = s & "   ""headline"": ""納期と品質のお約束を保険で裏づけ、法人向けの受注をとりやすくします""," & vbLf
    s = s & "   ""body"": ""贈答や記念品の受注では、期日どおりに納められるかどうかが選ばれる理由になります。万一のときの代替調達や再製造の費用を保険で引き受けることで、お約束をしやすくします。""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""premise"": ""本資料は、公開情報のみを用いて貴社の事業構造と一般的なリスクを仮説としてまとめたものです。いまのご契約、損害の履歴、財務の数値、設備の仕様は確認しておりません。評価は対話を始めるための仮のものです。""," & vbLf
    s = s & " ""structure"": [" & vbLf
    s = s & "  ""事業構造とリスクの全体像""," & vbLf
    s = s & "  ""保険で備えられるリスク""," & vbLf
    s = s & "  ""保険だけでは備えにくいリスク""," & vbLf
    s = s & "  ""成長を後押しする活用""," & vbLf
    s = s & "  ""全体像と進め方""" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""business"": {" & vbLf
    s = s & "  ""areas"": [" & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""製造(浜松本社工場)""," & vbLf
    s = s & "    ""desc"": ""主力の焼菓子と生菓子を製造しています。季節限定品の増産期に負荷が集中します。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""製造(浜北工場)""," & vbLf
    s = s & "    ""desc"": ""焼菓子の一部工程を担っています。本社工場の負荷を分け合う関係にあります。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""店舗販売""," & vbLf
    s = s & "    ""desc"": ""直営店での対面販売です。観光の人出に売上が左右されます。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""通信販売""," & vbLf
    s = s & "    ""desc"": ""自社の通信販売サイトを刷新し、直接のお取引が増えています。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""卸・法人向け""," & vbLf
    s = s & "    ""desc"": ""小売店と法人のお取引先へ卸しています。期日どおりの納品が前提です。""" & vbLf
    s = s & "   }" & vbLf
    s = s & "  ]," & vbLf
    s = s & "  ""factors"": [" & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""地域への集中""," & vbLf
    s = s & "    ""tag"": ""公開情報より""," & vbLf
    s = s & "    ""desc"": ""製造も販売も浜松に集まっているため、地域の災害が全体に及びます。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""原材料の産地""," & vbLf
    s = s & "    ""tag"": ""公開情報より""," & vbLf
    s = s & "    ""desc"": ""果実と乳製品は産地の作柄に左右され、調達が不安定になることがあります。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""季節の増産""," & vbLf
    s = s & "    ""tag"": ""当社の想定""," & vbLf
    s = s & "    ""desc"": ""贈答の時期に生産が集中し、確認の工程が薄くなりやすい状況です。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""通信販売の刷新""," & vbLf
    s = s & "    ""tag"": ""公開情報より""," & vbLf
    s = s & "    ""desc"": ""お客さまの情報を預かる範囲が広がり、守るべき対象が増えています。""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""name"": ""配送の委託先""," & vbLf
    s = s & "    ""tag"": ""当社の想定""," & vbLf
    s = s & "    ""desc"": ""通信販売の配送を1社に任せている場合、代わりの手段が用意しにくくなります。""" & vbLf
    s = s & "   }" & vbLf
    s = s & "  ]," & vbLf
    s = s & "  ""facts"": [" & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""label"": ""本社所在地""," & vbLf
    s = s & "    ""value"": ""静岡県浜松市""," & vbLf
    s = s & "    ""note"": ""公開情報より""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""label"": ""工場""," & vbLf
    s = s & "    ""value"": ""2拠点""," & vbLf
    s = s & "    ""note"": ""本社工場と浜北工場""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""label"": ""販売の経路""," & vbLf
    s = s & "    ""value"": ""店舗・通信販売・卸""," & vbLf
    s = s & "    ""note"": ""3つの経路""" & vbLf
    s = s & "   }," & vbLf
    s = s & "   {" & vbLf
    s = s & "    ""label"": ""主な原材料""," & vbLf
    s = s & "    ""value"": ""小麦粉・バター・果実""," & vbLf
    s = s & "    ""note"": ""産地の作柄に左右されます""" & vbLf
    s = s & "   }" & vbLf
    s = s & "  ]" & vbLf
    s = s & " }," & vbLf
    s = s & " ""categories_note"": {" & vbLf
    s = s & "  ""heavy"": ""設備と事業継続の分類に3件が集まりました。""," & vbLf
    s = s & "  ""meaning"": ""製造の1か所が止まると出荷と売上の全体に広がるため、復旧までの時間を短くする備えが効きます。""" & vbLf
    s = s & " }," & vbLf
    s = s & " ""headline"": {" & vbLf
    s = s & "  ""riskmap"": ""浸水と情報の流出が最も重く、次に原材料の調達難と人手不足が並びます""," & vbLf
    s = s & "  ""classes"": ""8件のうち3件は保険で備えやすく、3件は補償条件の設計が要り、2件は経営の施策が中心です""," & vbLf
    s = s & "  ""priority"": ""浸水と情報の流出は補償条件の設計が鍵で、調達難と人手不足は経営の施策が主役です""," & vbLf
    s = s & "  ""hard"": ""保険だけでは備えにくい4件には、経営の施策と保険の組み合わせで備えます""," & vbLf
    s = s & "  ""ideas"": ""8案のうち、事業への効果が高く実現しやすい4案を優先候補としてご提案します""," & vbLf
    s = s & "  ""four"": ""納期と品質と体験と情報という、失敗できない場面の不安を保険が引き受けます""," & vbLf
    s = s & "  ""themes"": ""3つのテーマで、経営の課題と保険と指標を一体で設計します""," & vbLf
    s = s & "  ""steps"": ""守る対象の見直しから始め、連鎖の見える化を経て、保険を成長につなげます""," & vbLf
    s = s & "  ""decide"": ""方向性と優先する成長支援案と次の進め方の3点をご相談させてください""," & vbLf
    s = s & "  ""share"": ""公開情報の限界を対話で埋め、評価と推奨する保険を実態に合わせて更新します""," & vbLf
    s = s & "  ""appendix"": ""8件のうち上位の3件を本文で優先して扱い、残りも正式提案時に評価を更新します""" & vbLf
    s = s & " }," & vbLf
    s = s & " ""hard_risks"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""risk_no"": 2," & vbLf
    s = s & "   ""horizon"": ""3年""," & vbLf
    s = s & "   ""background"": ""果実と乳製品は産地の作柄と輸入価格に左右され、調達が滞ると生産計画が遅れます。""," & vbLf
    s = s & "   ""approach"": ""仕入先を複数にし、在庫の持ち方を見直したうえで、費用の一部を保険で受けます。""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""risk_no"": 4," & vbLf
    s = s & "   ""horizon"": ""現在""," & vbLf
    s = s & "   ""background"": ""短時間の勤務の方の比率が高く、増産期に人手を確保できない状況が起こり得ます。""," & vbLf
    s = s & "   ""approach"": ""応援の体制と多能工の育成を進め、労災の上乗せ補償の対象範囲を確認します。""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""risk_no"": 6," & vbLf
    s = s & "   ""horizon"": ""5年""," & vbLf
    s = s & "   ""background"": ""国内の菓子の市場は緩やかに縮小しており、既存商品の販売数量が伸び悩みます。""," & vbLf
    s = s & "   ""approach"": ""通信販売の拡大と新商品の開発で需要をつくります。保険での備えは限られます。""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""risk_no"": 8," & vbLf
    s = s & "   ""horizon"": ""3年""," & vbLf
    s = s & "   ""background"": ""通信販売の配送を担う委託先に支障が出ると、代わりの手段が無いまま配送が滞ります。""," & vbLf
    s = s & "   ""approach"": ""委託先を複数にする検討を進め、止まったときの費用を保険で受けられるか確認します。""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""ideas"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""法人ギフトの納品保証""," & vbLf
    s = s & "   ""aim"": ""期日どおりに納められない不安を引き受け、贈答の受注を取りやすくします。""," & vbLf
    s = s & "   ""effect"": 5," & vbLf
    s = s & "   ""difficulty"": ""中""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""工場見学と体験の傷害補償""," & vbLf
    s = s & "   ""aim"": ""体験のご案内に安心を添え、観光のお客さまを呼び込みます。""," & vbLf
    s = s & "   ""effect"": 4," & vbLf
    s = s & "   ""difficulty"": ""低""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""通信販売の情報保護の備え""," & vbLf
    s = s & "   ""aim"": ""お客さまの情報を預かる責任を明確にし、購入の障壁を下げます。""," & vbLf
    s = s & "   ""effect"": 5," & vbLf
    s = s & "   ""difficulty"": ""中""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""取引先の支払い能力への備え""," & vbLf
    s = s & "   ""aim"": ""新しいお取引先を開拓するときの回収の不安を小さくします。""," & vbLf
    s = s & "   ""effect"": 4," & vbLf
    s = s & "   ""difficulty"": ""中""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""原材料の調達が滞ったときの費用補償""," & vbLf
    s = s & "   ""aim"": ""産地の作柄に左右される調達の不安を和らげます。""," & vbLf
    s = s & "   ""effect"": 3," & vbLf
    s = s & "   ""difficulty"": ""高""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""復旧までの時間を短くする点検""," & vbLf
    s = s & "   ""aim"": ""止まった時間を短くする備えを、点検の仕組みとあわせて整えます。""," & vbLf
    s = s & "   ""effect"": 3," & vbLf
    s = s & "   ""difficulty"": ""中""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""従業員の福利厚生の上乗せ""," & vbLf
    s = s & "   ""aim"": ""働く方の安心を高め、増産期の人手の確保につなげます。""," & vbLf
    s = s & "   ""effect"": 2," & vbLf
    s = s & "   ""difficulty"": ""低""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""催事と出店の中止に備える補償""," & vbLf
    s = s & "   ""aim"": ""天候などで催事が中止になったときの費用を受けます。""," & vbLf
    s = s & "   ""effect"": 2," & vbLf
    s = s & "   ""difficulty"": ""中""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""four"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""法人ギフトの納品保証""," & vbLf
    s = s & "   ""aim"": ""期日どおりの納品というお約束を、保険で裏づけます。""," & vbLf
    s = s & "   ""mechanism"": ""偶然の事故で約束した数量や期日に納められない場合の、緊急輸送や代替調達や再製造の追加費用を保険で受けます。""," & vbLf
    s = s & "   ""insurance"": ""費用利益の保険(一般名称)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""工場見学と体験の傷害補償""," & vbLf
    s = s & "   ""aim"": ""体験のご案内に安心を添えます。""," & vbLf
    s = s & "   ""mechanism"": ""見学や体験の最中のけがについて、治療の費用をお支払いする仕組みを、参加者ごとにまとめてご用意します。""," & vbLf
    s = s & "   ""insurance"": ""傷害保険(一般名称)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""通信販売の情報保護の備え""," & vbLf
    s = s & "   ""aim"": ""預かる情報への責任を明確にします。""," & vbLf
    s = s & "   ""mechanism"": ""情報が外に出たときの調査や連絡や賠償の費用を保険で受け、購入いただくときの不安を小さくします。""," & vbLf
    s = s & "   ""insurance"": ""サイバー保険(一般名称)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""取引先の支払い能力への備え""," & vbLf
    s = s & "   ""aim"": ""新しいお取引の回収の不安を小さくします。""," & vbLf
    s = s & "   ""mechanism"": ""お取引先が支払えなくなったときの売掛金の損失を保険で受け、新しいお取引先を増やしやすくします。""," & vbLf
    s = s & "   ""insurance"": ""取引信用保険(一般名称)""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""theme_table"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""theme"": ""事業を止めない""," & vbLf
    s = s & "   ""issues"": ""浸水と設備の停止で出荷が止まること""," & vbLf
    s = s & "   ""insurance"": ""火災保険(水災を含む)と利益の保険(一般名称)""," & vbLf
    s = s & "   ""kpi"": ""復旧までの目標時間""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""theme"": ""ブランドを守る""," & vbLf
    s = s & "   ""issues"": ""表示の誤りと情報の流出""," & vbLf
    s = s & "   ""insurance"": ""生産物賠償責任保険とサイバー保険(一般名称)""," & vbLf
    s = s & "   ""kpi"": ""回収の対象となった件数""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""theme"": ""成長を後押しする""," & vbLf
    s = s & "   ""issues"": ""納期と支払いのお約束""," & vbLf
    s = s & "   ""insurance"": ""費用利益の保険と取引信用保険(一般名称)""," & vbLf
    s = s & "   ""kpi"": ""法人向けの受注の件数""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""steps"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""守る対象を見直す""," & vbLf
    s = s & "   ""who"": ""当社""," & vbLf
    s = s & "   ""desc"": ""建物と設備だけでなく、ブランドと納期とお客さまとの接点と技能を、重要な資産として棚卸しします。""," & vbLf
    s = s & "   ""ref"": ""Section 1(事業構造と5つのリスク要因)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""連鎖を見える化する""," & vbLf
    s = s & "   ""who"": ""当社と貴社""," & vbLf
    s = s & "   ""desc"": ""1か所の事故がどこまで広がるかを、製造から出荷までの流れに沿って書き出します。""," & vbLf
    s = s & "   ""ref"": ""Section 1(リスクの全体像とリスクマップ)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""保険での備え方を整理する""," & vbLf
    s = s & "   ""who"": ""当社と貴社""," & vbLf
    s = s & "   ""desc"": ""いまのご契約と必要な備えを並べ、補償条件の設計が要る部分を明らかにします。""," & vbLf
    s = s & "   ""ref"": ""Section 2(3分類と優先リスク)""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""保険を成長につなげる""," & vbLf
    s = s & "   ""who"": ""当社""," & vbLf
    s = s & "   ""desc"": ""納期や体験や情報のお約束を保険で裏づけ、受注の障壁を下げる使い方をご提案します。費用の目安は正式提案時にお示しします。""," & vbLf
    s = s & "   ""ref"": ""Section 4(成長を後押しする保険の活用)""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""decisions"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""3つのテーマの方向性""," & vbLf
    s = s & "   ""options"": ""事業を止めない・ブランドを守る・成長を後押しするという組み立てが、経営の課題の認識と合っているか。""," & vbLf
    s = s & "   ""note"": ""3つのテーマの優先順位と、加えるべき論点の有無""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""優先して検討する成長支援案""," & vbLf
    s = s & "   ""options"": ""優先候補の4案のうち、どれから具体化するか。""," & vbLf
    s = s & "   ""note"": ""受注や予約への効き方と、進めやすさ""" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""title"": ""次の進め方""," & vbLf
    s = s & "   ""options"": ""ご共有いただく事項の範囲と、次回の打ち合わせの時期。""," & vbLf
    s = s & "   ""note"": ""本日は最終の結論をお願いするものではありません""" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""share_items"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""直近3期の売上の構成(経路別)""," & vbLf
    s = s & "   ""group"": ""事業・生産""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""主要原材料の仕入先の数と集中の度合い""," & vbLf
    s = s & "   ""group"": ""事業・生産""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""工場ごとの設備と生産能力""," & vbLf
    s = s & "   ""group"": ""事業・生産""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""通信販売の配送の委託先と代わりの手段""," & vbLf
    s = s & "   ""group"": ""事業・生産""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""いまご契約の保険の一覧と補償の条件""," & vbLf
    s = s & "   ""group"": ""保険・契約""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""過去5年の事故と保険金のお支払いの履歴""," & vbLf
    s = s & "   ""group"": ""保険・契約""," & vbLf
    s = s & "   ""priority"": true" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""建物と設備の再取得の価額""," & vbLf
    s = s & "   ""group"": ""保険・契約""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""情報を守るための対策の実施状況""," & vbLf
    s = s & "   ""group"": ""情報・体制""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""従業員の構成と増産期の人員の計画""," & vbLf
    s = s & "   ""group"": ""情報・体制""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""text"": ""事業継続計画の有無と発動の基準""," & vbLf
    s = s & "   ""group"": ""情報・体制""," & vbLf
    s = s & "   ""priority"": false" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]," & vbLf
    s = s & " ""notes"": [" & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 1," & vbLf
    s = s & "   ""read"": ""本日はお時間をいただきありがとうございます。公開情報から見えた姿をご説明します。""," & vbLf
    s = s & "   ""ask"": ""資料はお手元にございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 2," & vbLf
    s = s & "   ""read"": ""ご提案の要旨です。3つのテーマで保険を組み直すことをご提案します。""," & vbLf
    s = s & "   ""ask"": ""3つの並びに違和感はございませんか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 3," & vbLf
    s = s & "   ""read"": ""まず貴社の事業構造とリスクの全体像をご説明します。""," & vbLf
    s = s & "   ""ask"": ""この順でよろしいでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 4," & vbLf
    s = s & "   ""read"": ""事業の5つの領域と、そこから見えるリスクの要因を整理しました。""," & vbLf
    s = s & "   ""ask"": ""認識と合っているところはございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 5," & vbLf
    s = s & "   ""read"": ""リスクを10のカテゴリーに分けて、漏れなく見ています。""," & vbLf
    s = s & "   ""ask"": ""足りない論点はございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 6," & vbLf
    s = s & "   ""read"": ""影響の大きさと起こりやすさで優先順位を付けました。""," & vbLf
    s = s & "   ""ask"": ""上位の並びはいかがでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 7," & vbLf
    s = s & "   ""read"": ""次に、いまの保険で備えられるリスクとその条件をご説明します。""," & vbLf
    s = s & "   ""ask"": ""ご契約の内容は後ほど確認させてください。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 8," & vbLf
    s = s & "   ""read"": ""8件を、備えやすさで3つに分けました。""," & vbLf
    s = s & "   ""ask"": ""この分け方はお使いになれそうですか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 9," & vbLf
    s = s & "   ""read"": ""優先するリスクごとに、対応する保険と確認したい点を並べました。""," & vbLf
    s = s & "   ""ask"": ""確認したい点にお心当たりはございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 10," & vbLf
    s = s & "   ""read"": ""ここからは、保険だけでは備えにくいリスクのお話です。""," & vbLf
    s = s & "   ""ask"": ""経営の施策のお話に入ってよろしいですか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 11," & vbLf
    s = s & "   ""read"": ""4件については、経営の施策と保険の組み合わせで備えます。""," & vbLf
    s = s & "   ""ask"": ""すでに進めていらっしゃる対策はございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 12," & vbLf
    s = s & "   ""read"": ""次に、成長を後押しする保険の使い方をご説明します。""," & vbLf
    s = s & "   ""ask"": ""攻めの話に移ってよろしいでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 13," & vbLf
    s = s & "   ""read"": ""8案を出し、効果と実現までの難易度で4案を優先候補にしました。""," & vbLf
    s = s & "   ""ask"": ""気になる案はどれでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 14," & vbLf
    s = s & "   ""read"": ""優先の4案について、狙いと仕組みと想定する保険をご説明します。""," & vbLf
    s = s & "   ""ask"": ""どの場面が一番お困りでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 15," & vbLf
    s = s & "   ""read"": ""ここからは、ご提案の全体像と進め方です。""," & vbLf
    s = s & "   ""ask"": ""残り時間は大丈夫でしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 16," & vbLf
    s = s & "   ""read"": ""3つのテーマごとに、課題と保険と指標を束ねました。""," & vbLf
    s = s & "   ""ask"": ""指標の置き方はいかがでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 17," & vbLf
    s = s & "   ""read"": ""4つのステップで進めます。役割と費用の扱いもお示しします。""," & vbLf
    s = s & "   ""ask"": ""進め方でご懸念はございますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 18," & vbLf
    s = s & "   ""read"": ""本日ご判断いただきたいことは3点です。""," & vbLf
    s = s & "   ""ask"": ""この3点でよろしいでしょうか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 19," & vbLf
    s = s & "   ""read"": ""次のステップとして、ご共有いただきたい事項をまとめました。""," & vbLf
    s = s & "   ""ask"": ""優先の4項目からお願いできますか。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 20," & vbLf
    s = s & "   ""read"": ""巻末に、今回扱ったリスクの一覧を付けています。""," & vbLf
    s = s & "   ""ask"": ""後ほどご確認ください。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 21," & vbLf
    s = s & "   ""read"": ""本資料の前提と、参照した公開情報です。""," & vbLf
    s = s & "   ""ask"": ""前提に誤りがあればお知らせください。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }," & vbLf
    s = s & "  {" & vbLf
    s = s & "   ""slide_no"": 22," & vbLf
    s = s & "   ""read"": ""本日はありがとうございました。次回までに評価を更新してお持ちします。""," & vbLf
    s = s & "   ""ask"": ""次回の日程を決めさせてください。""," & vbLf
    s = s & "   ""probe"": [" & vbLf
    s = s & "    ""もう少し詳しくお聞かせいただけますか。""" & vbLf
    s = s & "   ]," & vbLf
    s = s & "   ""follow"": [" & vbLf
    s = s & "    ""次回までに当社で整理してお持ちします。""" & vbLf
    s = s & "   ]" & vbLf
    s = s & "  }" & vbLf
    s = s & " ]" & vbLf
    s = s & "}"
    BuildS5Json = s
End Function
